config/routes.rb
Rails.application.routes.draw do
  # get 'tasks/index'

  # get 'tasks/show'

  # get 'tasks/new'

  # get 'tasks/create'

  # get 'tasks/edit'

  # get 'tasks/update'

  # get 'tasks/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy ]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
     @task = Task.new(task_params)
     @task.save
     redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :content)
  end

   def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>These are your tasks:</h1>
<ul><% @tasks.each do |task| %>
  <li>
  <%= link_to task.name, task_path(task) %>
  <%= task.content %>
  <%= link_to 'Edit', edit_task_path(task), method: :get, data: { confirm: 'Are you sure you want to edit this task?'} %>
  <%= link_to 'Remove', task_path(task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?'} %>
  </li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<li>
<%= @task.name %> <%= @task.content %>
</li>

<%= link_to "go back to the tasks", tasks_path  %>